print('Please enter the following:\n')
adjective = input('adjective: ')
animal_0 = input('animal: ')
verb_0 = input('verb: ')
exclamation = input('exclamation: ')
verb_1 = input('verb: ')
verb_2 = input('verb: ')
animal_1 = input('animal:')
print('\nYour story is:')
print(f'\nThe other day, I was really in trouble. It all started when I saw a very {adjective.lower()} {animal_0.lower()} {verb_0.lower()} down the hallway. "{exclamation.capitalize()}!" I yelled. But all I could think to do was to {verb_1.lower()} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_2.lower()} right in front of my family. When i put my glass i see that the {animal_0.lower()} was a {animal_1.upper()}!')